#include <a_samp>

stock LoadTextLabels() {
    Create3DTextLabel("{A020F0}Armario Ballas\n{FFFFFF} Pressione {A020F0}'Y' {FFFFFF}para abrir.", 0xFFFFFFFF, 305.71868896, 307.09603881, 999.14843750, 10, 0); // Armario Ballas
    Create3DTextLabel("{A020F0}Armario Groove Street\n{FFFFFF} Pressione {A020F0}'Y' {FFFFFF}para abrir.", 0xFFFFFFFF, 2498.10839843, -1705.58862304, 1014.74218750, 10, 0); // Armario GSF
    Create3DTextLabel("{A020F0}Armario The Lost MC\n{FFFFFF} Pressione {A020F0}'Y' {FFFFFF}para abrir.", 0xFFFFFFFF, 322.04821777, 1116.99633789, 1083.88281250, 10, 0); // Armario TLMC
    Create3DTextLabel("{A020F0}Armario Outlaws MC\n{FFFFFF} Pressione {A020F0}'Y' {FFFFFF}para abrir.", 0xFFFFFFFF, 504.94070434, -76.66397094, 998.75781250, 10, 0); // Armario Outlaws
    Create3DTextLabel("{A020F0}Armario Forcas Armadas\n{FFFFFF} Pressione {A020F0}'Y' {FFFFFF}para abrir.", 0xFFFFFFFF, 254.422241, 75.341224, 1003.640625, 15, 0); // Armario Forcas Armadas

    Create3DTextLabel("{A020F0}Loterica\n{FFFFFF}Presssione {A020F0}'F' {FFFFFF}ou {A020F0}'ENTER'\n{FFFFFF}para entrar.", 0xFFFFFFFF, 1631.80700683, -1172.25427246, 24.07812500, 20, 0); // Exterior Loterica
    Create3DTextLabel("{A020F0}Loterica\n{FFFFFF}Pressione {A020F0}'F' {FFFFFF}ou {A020F0}'ENTER'\n{FFFFFF}para sair.", 0xFFFFFFFF, 834.1140, 7.5438, 1004.1797, 20, 0); // Interior Loterica
    
    Create3DTextLabel("{A020F0}Loja de Armas\n{FFFFFF}Pressione {A020F0}'F' {FFFFFF}ou {A020F0}'ENTER'\n{FFFFFF}para entrar.", 0xFFFFFFFF, 1368.1648, -1279.7548, 13.5469, 20, 0); // Exterior Loterica
    Create3DTextLabel("{A020F0}Loja de Armas\n{FFFFFF}Pressione {A020F0}'F' {FFFFFF}ou {A020F0}'ENTER'\n{FFFFFF}para sair.", 0xFFFFFFFF, 285.352416, -41.336860, 1001.515625, 20, 0); // Interior Loja de Armas LS

    Create3DTextLabel("{A020F0}Pizzaria\n{FFFFFF}Pressione {A020F0}'F' {FFFFFF}ou {A020F0}'ENTER'\n{FFFFFF}para entrar.", 0xFFFFFFFF, 2104.568115, -1806.430541, 13.554687, 20, 0); // Exterior Pizzaria LS
    Create3DTextLabel("{A020F0}Pizzaria\n{FFFFFF}Pressione {A020F0}'F' {FFFFFF}ou {A020F0}'ENTER'\n{FFFFFF}para sair.", 0xFFFFFFFF, 372.348846, -133.160736, 1001.492187, 20, 0); // Interior Pizzaria

    Create3DTextLabel("{A020F0}Menu de Armas\n{FFFFFF} Pressione {A020F0}'Y' {FFFFFF}para abrir.", 0xFFFFFFFF, 296.175262, -37.462314, 1001.515625, 10, 0); // Menu Armas LS
    Create3DTextLabel("{FFFFFF}/dinamitar", 0xFFFFFFFF, 824.977783, 10.231960, 1004.179, 20, 0);
    Create3DTextLabel("{FFFFFF}/roubar", 0xFFFFFFFF, 820.70001, 11.6, 1003.6, 5, 0);

    Create3DTextLabel("{A020F0}Pista de Skate\n{FFFFFF} Pressione {A020F0}'H' {FFFFFF}para dominar.", 0xFFFFFFFF, 1884.66064453, -1428.08288574, 10.35937500, 50, 0); // Pista de Skate
    Create3DTextLabel("{A020F0}Casarao\n{FFFFFF} Pressione {A020F0}'H' {FFFFFF}para dominar.", 0xFFFFFFFF, 1180.85986328, -2036.71289062, 69.00781250, 50, 0); // Casarao
    Create3DTextLabel("{A020F0}Alojamento\n{FFFFFF} Pressione {A020F0}'H' {FFFFFF}para dominar.", 0xFFFFFFFF, 895.35870361, -1251.42553710, 15.26383495, 50, 0); // Alojamento
    Create3DTextLabel("{A020F0}Construcao\n{FFFFFF} Pressione {A020F0}'H' {FFFFFF}para dominar.", 0xFFFFFFFF, -2080.60449218, 208.25245666, 35.31754684, 50, 0); // Construcao
    Create3DTextLabel("{A020F0}Madereira\n{FFFFFF} Pressione {A020F0}'H' {FFFFFF}para dominar.", 0xFFFFFFFF, -521.10455322, -102.89633941, 63.29875564, 50, 0); // Madereira

    Create3DTextLabel("{FFFFFF} Pressione {A020F0}'F' {FFFFFF}ou {A020F0}'ENTER'\n{FFFFFF}para sair.", 0xFFFFFFFF, 300.85043334, 300.75317382, 999.14843750, 20, 0); // Interior Base Ballas
    Create3DTextLabel("{FFFFFF} Pressione {A020F0}'F' {FFFFFF}ou {A020F0}'ENTER'\n{FFFFFF}para entrar.", 0xFFFFFFFF, 2043.81689453, -1106.85180664, 24.46660804, 20, 0); // Exterior Base Ballas
    Create3DTextLabel("{FFFFFF} Pressione {A020F0}'F' {FFFFFF}ou {A020F0}'ENTER'\n{FFFFFF}para sair.", 0xFFFFFFFF, 2495.98242187, -1692.08422851, 1014.74218750, 20, 0); // Interior Base GSF
    Create3DTextLabel("{FFFFFF} Pressione {A020F0}'F' {FFFFFF}ou {A020F0}'ENTER'\n{FFFFFF}para entrar.", 0xFFFFFFFF, 2495.47680664, -1690.51440429, 14.76562500, 20, 0); // Exterior Base GSF
    Create3DTextLabel("{FFFFFF} Pressione {A020F0}'F' {FFFFFF}ou {A020F0}'ENTER'\n{FFFFFF}para sair.", 0xFFFFFFFF, 318.29431152, 1114.48205566, 1083.88281250, 20, 0); // Interior Base TLMC
    Create3DTextLabel("{FFFFFF} Pressione {A020F0}'F' {FFFFFF}ou {A020F0}'ENTER'\n{FFFFFF}para entrar.", 0xFFFFFFFF, -69.21263885, -1546.24243164, 3.00430750, 20, 0); // Exterior Base TLMC
    Create3DTextLabel("{FFFFFF} Pressione {A020F0}'F' {FFFFFF}ou {A020F0}'ENTER'\n{FFFFFF}para sair.", 0xFFFFFFFF, 501.95877075, -68.15670013, 998.75781250, 20, 0); // Interior Base OUTL
    Create3DTextLabel("{FFFFFF} Pressione {A020F0}'F' {FFFFFF}ou {A020F0}'ENTER'\n{FFFFFF}para entrar.", 0xFFFFFFFF, 646.77307128, -511.14227294, 16.33593750, 20, 0); // Exterior Base OUTL
    Create3DTextLabel("{FFFFFF} Presssione {A020F0}'F' {FFFFFF}ou {A020F0}'ENTER'\n{FFFFFF}para sair.", 0xFFFFFFFF, 246.726730, 62.542018, 1003.640625, 20, 0); // Interior Base FA
    Create3DTextLabel("{FFFFFF} Pressione {A020F0}'F' {FFFFFF}ou {A020F0}'ENTER'\n{FFFFFF}para entrar.", 0xFFFFFFFF, 192.733489, 1931.366943, 17.640625, 20, 0); // Exterior Base FA
    
    Create3DTextLabel("{A020F0}Ayman al-Zawahiri\n{FFFFFF} Pressione {A020F0}'Y' {FFFFFF}para interagir.", 0xFFFFFFFF, 2351.5095, -648.0492, 128.0547, 20, 0, 0);
    return 1;
}